(() => {

  //variables
  const model = document.querySelector("#model");
  const hotspots = document.querySelectorAll(".Hotspot");

  const infoboxContainer = document.querySelector("#infoboxes");

  const materialTemplate = document.querySelector("#material-template");
  const materialsContainer = document.querySelector("#materials");
  const materialsList = document.querySelector("#material-list");

  let spinner = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="209px" height="209px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
  <path fill="none" stroke="#e90c59" stroke-width="8" stroke-dasharray="135.9921319580078 120.59679626464845" d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z" stroke-linecap="round" style="transform:scale(0.8300000000000001);transform-origin:50px 50px">
    <animate attributeName="stroke-dashoffset" repeatCount="indefinite" dur="2.941176470588235s" keyTimes="0;1" values="0;256.58892822265625"/>
  </path>
  <!-- [ldio] generated by https://loading.io/ --></svg>`;

  function getinfoboxes() {

    fetch("https://swiftpixel.com/earbud/api/infoboxes")
    .then(response => response.json())
    .then(infoboxes => {
      console.log(infoboxes);
      
      infoboxes.forEach((infobox, index) => {

        let selected = document.querySelector(`#hotspot-${index+1}`);

        const li = document.createElement("li");

        const img = document.createElement("img");
        img.src = `images/${infobox.thumbnail}`;

        const h3 = document.createElement("h3");
        h3.textContent = infobox.heading;

        const p = document.createElement("p");
        p.textContent = infobox.description;
        
        selected.appendChild(li);
        selected.appendChild(img);
        selected.appendChild(h3);
        selected.appendChild(p);
        
      })

    })
    .catch(error => console.error(error)); 
  }
  getinfoboxes();

  //functions
  function modelLoaded() {
    hotspots.forEach(hotspot => {
      hotspot.style.display = "block";
    });
  }

  function loadInfoBoxes() {

    materialsContainer.innerHTML = spinner;

    fetch("https://swiftpixel.com/earbud/api/materials")
    .then(response => response.json())
    .then(materials => {
      console.log(materials);
      
      materials.forEach(material => {
      
      const clone = materialTemplate.content.cloneNode(true);

      const materialHeading = clone.querySelector(".material-heading");
      materialHeading.textContent = material.heading;

      const materialDescription = clone.querySelector(".material-description");
      materialDescription.textContent = material.description;

      materialsList.appendChild(clone);
    
    });
    
    materials.innerHTML = "";
  })
  .catch(error => console.error("Error fetching materials",error)); 
}
loadInfoBoxes();

  function showInfo() {
    let selected = document.querySelector(`#${this.slot}`);
    gsap.to(selected, 1, { autoAlpha: 1 });
  }

  function hideInfo() {
    let selected = document.querySelector(`#${this.slot}`);
    gsap.to(selected, 1, { autoAlpha: 0 });
  }

  //Event listeners
  model.addEventListener("load", modelLoaded);

  hotspots.forEach(function (hotspot) {
    hotspot.addEventListener("mouseenter", showInfo);
    hotspot.addEventListener("mouseleave", hideInfo);
  });

})();

