(() => {

    //variables
  const model = document.querySelector("#model");
  const hotspots = document.querySelectorAll(".Hotspot");

  const materialTemplate = document.querySelector("#material-template");
  const materialList = document.querySelector("#material-list");     

  //functions
  function modelLoaded() {
    hotspots.forEach(hotspot => {
      hotspot.style.display = "block";
    });
  }

  function loadInfoBoxes() {

    fetch("https://swiftpixel.com/earbud/api/infoboxes")
    .then(response => response.json())
    .then(infoBoxes => {
        console.log(infoBoxes);

        let ul = document.createElement("ul");

        infoBoxes.results.forEach(result => {

            const li = document.createElement("li");

            const h3 = document.createElement("h3");
            h3.textContent = `${result.heading}`;

            const p = document.createElement("p");
            p.textContent = `${result.description}`;

            const img = document.createElement("img");
            img.src = `{images/${result.thumbnail}}`;

        li.appendChild(h3);
        li.appendChild(p);
        ul.appendChild(li);

    });

    materialList.innerHTML = "";
    materialList.appendChild(ul);

    })
    .catch(error => console.error(error));
}

loadInfoBoxes();


const materialsList = document.querySelector("#material-list");

let spinner = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="215px" height="215px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
    // <path fill="none" stroke="#e90c59" stroke-width="9" stroke-dasharray="128.29446411132812 128.29446411132812" d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z" stroke-linecap="round" style="transform:scale(0.91);transform-origin:50px 50px">
    //   <animate attributeName="stroke-dashoffset" repeatCount="indefinite" dur="1.3888888888888888s" keyTimes="0;1" values="0;256.58892822265625"/>
    // </path>
    // <!-- [ldio] generated by https://loading.io/ --></svg>`;
    
function loadMaterialInfo() {

    materialList.innerHTML = spinner;

    fetch("https://swiftpixel.com/earbud/api/materials")
    .then(response => response.json())
    .then(materials => {
        console.log(materials);

        let ul = document.createElement("ul");

        materials.result.forEach(result => {

            const li = document.createElement("li");

            const h3 = document.createElement("h3");
            h3.textContent = result.heading;

            const p = document.createElement("p");
            p.textContent = result.description;

            li.appendChild(h3);
            li.appendChild(p);
            ul.appendChild(li);

        });

        loadMaterialInfo.innerHTML = "";
        loadMaterialInfo.appendChild(ul);

    })
    .catch(error => console.error(error));
}

loadMaterialInfo();

materialListData.forEach(material => {
    //Make a copy of the template
    const clone = materialTemplate.content.cloneNode(true);

    const materialHeading = clone.querySelector(".material-heading");
    materialHeading.textContent = material.heading;

    const materialDescription = clone.querySelector(".material-description");
    materialDescription.textContent = material.description;

    //aooend the populated templated to the ul
    materialList.appendChild(clone);
    console.log(clone);
  })


function showInfo() {
  let selected = document.querySelector(`#${this.slot}`);
  gsap.to(selected, 1, { autoAlpha: 1 });
}

function hideInfo() {
  let selected = document.querySelector(`#${this.slot}`);
  gsap.to(selected, 1, { autoAlpha: 0 });
}

//Event listeners
model.addEventListener("load", modelLoaded);

hotspots.forEach(function (hotspot) {
  hotspot.addEventListener("mouseenter", showInfo)
  hotspot.addEventListener("mouseleave", hideInfo)
  });

})();